title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

collections:
  projects:
    output: true
    permalink: /project/:name

defaults:
  - scope:
      path: "_projects/*.md"
    values:
      layout: project
      
plugins:
  - jekyll-feed
  - jekyll-sitemap

extlinks:
  attributes: { rel: nofollow noopener noreferrer, target: _blank }

include:
  - _pages

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE
